import * as FileSystem from "expo-file-system";
import * as Sharing from "expo-sharing";

type ReportData = {
  patientName: string;
  reportDate: string;
  stats: Array<{
    label: string;
    value: string;
  }>;
  glucoseTrends: Array<{
    day: string;
    glucose: number;
  }>;
  timeInRange: {
    inRange: number;
    high: number;
    low: number;
  };
  recommendations: string[];
};

export const ReportService = {
  async generateReport(data: ReportData): Promise<{
    success: boolean;
    content?: string;
    htmlContent?: string;
    error?: string;
  }> {
    try {
      // Generate text content
      const textContent = this.generateTextReportContent(data);
      // Generate HTML content for PDF
      const htmlContent = this.generateHTMLReportContent(data);

      return {
        success: true,
        content: textContent,
        htmlContent: htmlContent,
      };
    } catch (error) {
      console.error("Error generating report:", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      };
    }
  },

  generateTextReportContent(data: ReportData): string {
    const lines = [];

    // Header
    lines.push("=".repeat(60));
    lines.push(`GLUCOSE GOOSE MEDICAL REPORT`);
    lines.push("=".repeat(60));
    lines.push("");
    lines.push(`Patient: ${data.patientName}`);
    lines.push(`Report Date: ${data.reportDate}`);
    lines.push("");

    // Statistics
    lines.push("STATISTICS");
    lines.push("-".repeat(30));
    data.stats.forEach((stat) => {
      lines.push(`${stat.label}: ${stat.value}`);
    });
    lines.push("");

    // Glucose Trends
    lines.push("GLUCOSE TRENDS (Last 7 Days)");
    lines.push("-".repeat(30));
    data.glucoseTrends.forEach((trend) => {
      lines.push(`${trend.day}: ${trend.glucose} mg/dL`);
    });
    lines.push(
      `Weekly Average: ${this.calculateAverage(data.glucoseTrends.map((t) => t.glucose))} mg/dL`,
    );
    lines.push("");

    // Time in Range
    lines.push("TIME IN RANGE DISTRIBUTION");
    lines.push("-".repeat(30));
    lines.push(`In Range (70-180 mg/dL): ${data.timeInRange.inRange}%`);
    lines.push(`High (>180 mg/dL): ${data.timeInRange.high}%`);
    lines.push(`Low (<70 mg/dL): ${data.timeInRange.low}%`);
    lines.push("");

    // Recommendations
    lines.push("RECOMMENDATIONS");
    lines.push("-".repeat(30));
    data.recommendations.forEach((rec, index) => {
      lines.push(`${index + 1}. ${rec}`);
    });
    lines.push("");

    // Footer
    lines.push("=".repeat(60));
    lines.push("Generated by Glucose Goose - Diabetes Management System");
    lines.push("=".repeat(60));

    return lines.join("\n");
  },

  generateHTMLReportContent(data: ReportData): string {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Glucose Goose Report - ${data.patientName}</title>
        <style>
          body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            text-align: center;
            border-bottom: 3px solid #2c3e50;
            padding-bottom: 20px;
            margin-bottom: 30px;
          }
          .header h1 {
            color: #2c3e50;
            margin-bottom: 5px;
          }
          .patient-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 25px;
            border-left: 4px solid #3498db;
          }
          .section {
            margin-bottom: 30px;
            page-break-inside: avoid;
          }
          .section-title {
            color: #2c3e50;
            border-bottom: 2px solid #eee;
            padding-bottom: 8px;
            margin-bottom: 15px;
            font-size: 18px;
          }
          .stats-grid {
            display: block;
          }
          .stat-item {
            marign-bottom: 12px;
          }
          .stat-label {
            font-size: 12px;
            color: #7f8c8d;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 5px;
          }
          .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #2c3e50;
          }
          .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
          }
          .table th {
            background: #f8f9fa;
            padding: 12px;
            text-align: left;
            border-bottom: 2px solid #ddd;
            color: #2c3e50;
          }
          .table td {
            padding: 10px 12px;
            border-bottom: 1px solid #eee;
          }
          .table tr:hover {
            background: #f8f9fa;
          }
          .recommendations {
            background: #fff8e1;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #ff9800;
          }
          .recommendation-item {
            margin-bottom: 10px;
            padding-left: 10px;
          }
          .time-in-range {
            display: block;
          }
          .time-item {
            margin-bottom: 12px;
          }
          .time-value {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
          }
          .time-label {
            font-size: 12px;
            color: #7f8c8d;
            text-transform: uppercase;
          }
          .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #eee;
            color: #7f8c8d;
            font-size: 12px;
          }
          .in-range { color: #27ae60; }
          .high { color: #e74c3c; }
          .low { color: #f39c12; }
          @media print {
            body {
              padding: 0;
            }
            .no-print {
              display: none;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Glucose Goose Medical Report</h1>
          <p>Diabetes Management Analysis</p>
        </div>
        
        <div class="patient-info">
          <h2>Patient Information</h2>
          <p><strong>Patient Name:</strong> ${data.patientName}</p>
          <p><strong>Report Date:</strong> ${data.reportDate}</p>
          <p><strong>Report ID:</strong> GG-${Date.now().toString().slice(-8)}</p>
        </div>
        
        <div class="section">
          <h2 class="section-title">Statistics Summary</h2>
          <div class="stats-grid">
            ${data.stats
              .map(
                (stat) => `
              <div class="stat-item">
                <div class="stat-label">${stat.label}</div>
                <div class="stat-value">${stat.value}</div>
              </div>
            `,
              )
              .join("")}
          </div>
        </div>
        
        <div class="section">
          <h2 class="section-title">Glucose Trends (Last 7 Days)</h2>
          <table class="table">
            <thead>
              <tr>
                <th>Day</th>
                <th>Glucose (mg/dL)</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${data.glucoseTrends
                .map((trend) => {
                  const status =
                    trend.glucose < 70
                      ? "Low"
                      : trend.glucose > 180
                        ? "High"
                        : "Normal";
                  const statusClass =
                    trend.glucose < 70
                      ? "low"
                      : trend.glucose > 180
                        ? "high"
                        : "in-range";
                  return `
                  <tr>
                    <td>${trend.day}</td>
                    <td>${trend.glucose} mg/dL</td>
                    <td class="${statusClass}">${status}</td>
                  </tr>
                `;
                })
                .join("")}
            </tbody>
          </table>
          <p><strong>Weekly Average:</strong> ${this.calculateAverage(data.glucoseTrends.map((t) => t.glucose))} mg/dL</p>
        </div>
        
        <div class="section">
          <h2 class="section-title">Time in Range Distribution</h2>
          <div class="time-in-range">
            <div class="time-item">
              <div class="time-value in-range">${data.timeInRange.inRange}%</div>
              <div class="time-label">In Range<br>(70-180 mg/dL)</div>
            </div>
            <div class="time-item">
              <div class="time-value high">${data.timeInRange.high}%</div>
              <div class="time-label">High<br>(>180 mg/dL)</div>
            </div>
            <div class="time-item">
              <div class="time-value low">${data.timeInRange.low}%</div>
              <div class="time-label">Low<br>(<70 mg/dL)</div>
            </div>
          </div>
          <p>Total monitored time: ${data.timeInRange.inRange + data.timeInRange.high + data.timeInRange.low}%</p>
        </div>
        
        <div class="section">
          <h2 class="section-title">Clinical Recommendations</h2>
          <div class="recommendations">
            ${data.recommendations
              .map(
                (rec, index) => `
              <div class="recommendation-item">
                <strong>${index + 1}.</strong> ${rec}
              </div>
            `,
              )
              .join("")}
          </div>
        </div>
        
        <div class="footer">
          <p>Generated by Glucose Goose - Diabetes Management System</p>
          <p>This report is for medical professional use only. Always verify with clinical judgment.</p>
          <p>Report generated on: ${new Date().toLocaleString()}</p>
          <p class="no-print">To save as PDF, use your browser's print function and select "Save as PDF"</p>
        </div>
      </body>
      </html>
    `;
  },

  calculateAverage(numbers: number[]): number {
    if (numbers.length === 0) return 0;
    const sum = numbers.reduce((a, b) => a + b, 0);
    return Math.round(sum / numbers.length);
  },
};
