import { StyleSheet } from "react-native";
import { VintageColors } from "../../colors";

export const styles = StyleSheet.create({
  legendContainer: {
    marginTop: 8,
    marginBottom: 4,
    maxHeight: 60,
    width: "100%",
  },
  legendHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 6,
    paddingHorizontal: 4,
  },
  legendTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: VintageColors.primaryText,
    flexShrink: 1,
  },
  legendHint: {
    fontSize: 10,
    color: VintageColors.secondaryText,
    fontStyle: "italic",
    marginLeft: "auto",
    flexShrink: 0,
  },
  legendScrollContent: {
    gap: 8,
    paddingRight: 20,
    flexDirection: "row",
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "white",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: VintageColors.border,
    minWidth: 120,
    maxWidth: 140,
    maxHeight: 36,
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
    flexShrink: 1,
  },
  legendIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    flexShrink: 0,
  },
  legendItemText: {
    fontSize: 11,
    color: VintageColors.primaryText,
    fontWeight: "500",
    flex: 1,
    flexShrink: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  infoModalContent: {
    backgroundColor: VintageColors.cardBackground,
    borderRadius: 16,
    width: "100%",
    maxWidth: 350,
    maxHeight: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: VintageColors.border,
  },
  infoHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: VintageColors.border,
    gap: 12,
  },
  infoIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.3)",
    flexShrink: 0,
  },
  infoTitleContainer: {
    flex: 1,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: VintageColors.primaryText,
    marginBottom: 4,
  },
  categoryBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  categoryText: {
    fontSize: 10,
    color: VintageColors.primaryText,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  closeInfoButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: VintageColors.lightBackground,
    borderWidth: 1,
    borderColor: VintageColors.border,
    flexShrink: 0,
  },
  infoBody: {
    padding: 16,
  },
  infoDescription: {
    fontSize: 14,
    color: VintageColors.primaryText,
    lineHeight: 20,
    marginBottom: 16,
  },
  colorInfo: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: VintageColors.border,
  },
  colorInfoTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: VintageColors.primaryText,
    marginBottom: 12,
  },
  colorGrid: {
    gap: 10,
  },
  colorExample: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  colorExampleIconContainer: {
    position: "relative",
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  colorDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.1)",
  },
  colorIconContainer: {
    position: "absolute",
    top: 8,
    left: 8,
    width: 16,
    height: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  colorLabel: {
    fontSize: 13,
    color: VintageColors.primaryText,
    flex: 1,
  },
});
