import { LegendItem } from "../../types/chart";
import {
  getInsulinIcon,
  getTargetIcon,
  getColorExplanation,
  CHART_COLORS,
} from "./chartUtils";

export const getLegendItems = (): LegendItem[] => [
  {
    id: "meal",
    name: "Meals",
    icon: "restaurant",
    color: CHART_COLORS.mealBreakfast,
    description: "Food intake events including breakfast, lunch, and dinner",
    category: "meal",
    showColorExplanation: true,
    colorExplanation: getColorExplanation("meal"),
  },
  {
    id: "snack",
    name: "Snacks",
    icon: "nutrition",
    color: CHART_COLORS.mornigSnack,
    description:
      "Snack events including morning, afternoon, and evening snacks",
    category: "snack",
    showColorExplanation: true,
    colorExplanation: getColorExplanation("snack"),
  },
  {
    id: "activity",
    name: "Activities",
    icon: "bicycle",
    color: CHART_COLORS.activityWalking,
    description:
      "Physical activities including walking, running, cycling, and more",
    category: "activity",
    showColorExplanation: true,
    colorExplanation: getColorExplanation("activity"),
  },
  {
    id: "insulin",
    name: "Insulin Bolus",
    icon: getInsulinIcon("Correction Bolus"),
    color: CHART_COLORS.bolusMedium,
    description: "Insulin bolus events for corrections or meals",
    category: "insulin",
    showColorExplanation: true,
    colorExplanation: getColorExplanation("insulin"),
  },
  {
    id: "temp-basal",
    name: "Temp Basals",
    icon: getInsulinIcon("Temp Basal"),
    color: CHART_COLORS.basalNormal,
    description: "Temporary basal rate adjustments",
    category: "basal",
    showColorExplanation: true,
    colorExplanation: getColorExplanation("basal"),
  },
  {
    id: "target",
    name: "Targets",
    icon: getTargetIcon("Custom"),
    color: CHART_COLORS.targetCustom,
    description: "Temporary glucose targets for different situations",
    category: "target",
    showColorExplanation: true,
    colorExplanation: getColorExplanation("target"),
  },
  {
    id: "device",
    name: "Device Events",
    icon: "bandage",
    color: CHART_COLORS.deviceSite,
    description: "Device maintenance events like site and sensor changes",
    category: "device",
    showColorExplanation: true,
    colorExplanation: getColorExplanation("device"),
  },
  {
    id: "note",
    name: "Notes",
    icon: "document-text",
    color: CHART_COLORS.note,
    description: "Notes, comments, and observations",
    category: "note",
    showColorExplanation: false,
  },
  {
    id: "announcement",
    name: "Announcements",
    icon: "bullhorn",
    color: CHART_COLORS.announcement,
    description: "Important announcements, alerts, and notifications",
    category: "announcement",
    showColorExplanation: false,
  },
  {
    id: "other",
    name: "Other Events",
    icon: "help-circle",
    color: CHART_COLORS.other,
    description: "Miscellaneous events not in other categories",
    category: "other",
    showColorExplanation: false,
  },
];
